website:
  title: "PROSJEKTTITTEL"
  site-url: "prosjektforkortelse.nifu.no"
  navbar:
    logo: "https://www.nifu.no/wp-content/uploads/logo_hvit.png"
    left:
      - text: "Om prosjektet"
        file: "main/om_prosjektet.qmd"
      - sidebar:reports
  sidebar:
    - id: reports
      title: "Rapporter"
      contents: "Rapporter"

execute:
  freeze: auto
  cache: false

metadata-files: # Defaults for all the organization's projects
  - _global.yaml # Must be in same folder/subfolder
