---
format: html
---

# Forord {#sec-forord .unnumbered}

Nordisk institutt for studier av innovasjon, forskning og utdanning (NIFU) har en rammeavtale for 2021--2025 med Utdanningsdirektoratet om å gjennomføre halvårlige spørreundersøkelser rettet mot skoler og skoleeiere. Undersøkelsene er kjent som Utdanningsdirektoratets spørringer.

Temaene for de enkelte undersøkelsene avtales fra gang til gang, og skal dekke Utdanningsdirektoratets kunnskapsbehov til enhver tid. Resultatene fra undersøkelsene offentliggjøres i NIFUs ordinære rapportserie, og foreligger nedlastbart i PDF-format på Utdanningsdirektoratets og NIFUs hjemmesider.

I spørringen gjennomført våren 2023 inngår fire respondentgrupper som er spurt om i alt 5 ulike temaer. Rapporten er i første rekke en tabellrapport, hvor det i liten grad gjøres mer inngående analyser. Det er ikke skrevet noe samlet sammendrag for denne rapporten, men leseren henvises til oppsummeringene ved slutten av hvert kapittel.

Prosjektleder for Utdanningsdirektoratets spørringer til Skole-Norge er Ann Cecilie Bergene, og hun har skrevet rapporten sammen med Ørjan Arnevig Samuelsen, Stephan Daus, Rønnaug Lyckander, Karl Solbue Vika og Torstein de Besche. Jens Brandi Grøgaard har kvalitetssikret rapporten. Kontaktperson hos Utdanningsdirektoratet er Sahra Ali Abdullahi Torjussen.

Vi takker 385 grunnskoler, 101 videregående skoler, 98 kommuner og elleve fylkeskommuner som har tatt seg tid til å besvare undersøkelsen, i konkurranse med mange andre viktige gjøremål.

Oslo, 12.06.2023

|               |                 |
|---------------|-----------------|
| Vibeke Opheim | Cay Gjerustad   |
| direktør      | forskningsleder |
