website:
  title: "NIFU-PROSJEKT: Endre tittel i _quarto.yaml"
  navbar:
    logo: "https://www.nifu.no/wp-content/uploads/logo_hvit.png"
    left:
      - id: main
        title: "Om prosjektet"
        contents: "main"
      - sidebar:reports
  sidebar:
    - id: reports
      title: "Rapporter"
      contents: "Rapporter"

project_no: '2XXXXX'
funder: Utdanningsdirektoratet
funder_address: Schweigaards gate 15B, 0191 Oslo
isbn: 978-82-327-0607-5
figure_table: true
table_table: true

execute:
  freeze: auto
  cache: false

metadata-files: # Defaults for all NIFU projects
  - _global.yaml # Must be in same folder/subfolder
